### ISSUE TITLE
Handle exceptions and add tests to all the functions

### ISSUE THREAD

**Issue by SebastinSanty** [AutolabJS/autolabcli#1]

**Comment by prasadtalasila** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/379    
https://www.npmjs.com/package/mock-inquirer

**Comment by prasadtalasila** [comment]
All the current efforts shall be directed towards creating a backward compatible Autolabcli. The new code shall be available in [autolabcli-ng](https://github.com/AutolabJS/autolabcli/tree/autolabcli-ng) branch.

The problem highlighted on this page is tracked through [refactoring](https://github.com/AutolabJS/autolabcli/wiki/Refactoring-scratch-pad) wiki page.
