### ISSUE TITLE
sample sequence diagram

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#21]
Sample plantUML code to generate the sequence diagrams

@startuml
Actor user
== Change Language ==
autonumber
user -> index : autolab git changelang
index -> git : changeLang()

== Change Language ==
autonumber
user -> index : autolab git changelang
index -> git : changeLang()
@enduml

**Comment by prasadtalasila** [comment]
[Proposed sequence diagram](http://www.plantuml.com/plantuml/uml/dPFDJeGm4CVlVOevkWTVO1FC6ZJHn8Dndw3024rAI-XqmxwzCotAIZo0bqxdu__xjtoS0kcHOc_LOqr-X1XmL4K1hyuG58NIaRoBVSLLQS7z0nZNu0H7a9RL5UU6L2wcBWkFATmTbA3A4JKXVE3WWs6FwqPkow0wQHTwc-2vAi3PuWaj_jUYITgrHQxUM9ITTYt2Ym-qv_n9nGCN7bpV8lK4-DlYZTUeURFNnlBojuaWPvFt63eeVTyR2ZiS1fQjsLARgUTOCH3EtaOotcq4XwHQi3ddWRpvVhac35PVmHf-zFxpHrtp9RHhmZQl3ksmE4d6JGcpo_Eq-OF7wVRGad5JWg1Ew1h-dRu0) by @vaibhavgarg11 
@SebastinSanty please verify the same.

Some of the function calls to git object has callback functions as parameters. They need to be included in the diagram itself.

**Comment by prasadtalasila** [comment]
A variation of the same diagram would be to add the calls to the library objects like chalk() from inside each of the functions. I added one function call in the sequence diagram for eeference.

**Comment by prasadtalasila** [comment]
http://www.plantuml.com/plantuml/uml/dLD1JiCm4Bpd5LPFSE03bOAA2XALE2321vncIIqsTXIlKVjxPfr2GmLIoiNhdV7Cn1jv5SKEaZekxhOI1fCY3KLPcertOigoi4c2JrqDL2bpSskSRsXlbaOfjZLw9yK8PXR2PIvNruLQhGUoGkQ5-X0TCWupVLiORRFsvDvcyn5LmsF4FJ7zDwB9slE84Pr4h7VMjsGUGvHBlZ-hSE031yzlaJar_1dnX3LPR2wDOIo_XwZbCUGvnPrPXwvp4Yz8w24xzrRiw5gb6eQc2fp41J_JE6RLoNRiSM3SVFrS5tks1yCEemzlt-ejBc5z4-TbxOZxKv9s8BKW9NT0CIn-1rnpeYaSV0nC83Yq4tmXjcPQlkgw02kXai5XqdygzJeF-zalY_RJwMW7KWkiLkGRFDjF

**Comment by vaibhavgarg11** [comment]
for help -> console does log() need to be specified twice ?

**Comment by prasadtalasila** [comment]
The sequence diagram serves the purpose of specifying the sequence of function calls. Hence we need to specify the call to log() twice.

**Comment by vaibhavgarg11** [comment]
http://www.plantuml.com/plantuml/uml/lLVDRjim3BxdAOISiaDVm42A3ks63bY1eTbzK6p65YfBhdwQvEr7od7iEAvZfUikjaL-_14_YhRlhEF6-LBElgPE6-OjcDbooNueuTXoEUFUQUNBDKf9nMvkcL0Px5Z2I2Nv6jV2pMfXqA9X4cwBBxEmGccgbTKIK25rtfKNNBwWT0zIwcr7iH6v17BaOETMUvLESFR07GdLYQCdxeg4RQJMvjEXmz9cZslfOS8kX7hrmc2f4rOPNLPkyUh1Ee7m5ZH7sfotoQeIIe6P8zY2EwnMpWZLTJc49je7aZIGJSWH4ql1MfJ3xeJdY68r4NC3e2x4f8Qm8JkUPSBq-k4FQhR25TftKya7-p2EYqYuWK0LCQSjXQMJT8z9Or6U0MK2ZzX-uh6Y_DDWsnwkUa-rb1nYYFnIrnmX_QppOHx6qO66hH4ElWi9YwdEwxQQXZtEWWlmOV4v1qJ20-0qkPA4BDZsIQYbyIH4LViJozVMgTv9qwq5LpcmHwnTJ9y6AmIy8R3VhK7tM9DnVRTsalk9Ly_n8JP1YPVXzCZbXzFxvMt1xdLP2cSZSglGh9yLoQBocVP2o2--3ne4tXChoah23JuI0YVlg3uD6wyXtNbDS-8mi4UTFqEf7OoYJgiok0jT7SXO-JMcmrPQUYhKH3vii6hPgDVaEJoWxuCanAy3NwZvlpOu4DL5wVG5N48d6hk4G72Uwnb6gnF4wQZfo7kDtchEFWAk2NUSLlyjOZDvfmISExwMaFocAxbqUe2bzytZQzhxu8WnYQhao9O7UouSgn4YmZjMs4hoFPC2tnrwSpnJD1Yuokoq4rY0hDhpHojKqWsZXDLvbOxYtgOQ-GYBxvdIVhxj9ly2KHNQf0syjPMv0vNXxzLV

**Comment by vaibhavgarg11** [comment]
The above link is to the detailed call graph along with the plantUML code written

Here's the link to final call graph 
http://www.plantuml.com/plantuml/png/lLVRRjim37tFLmXvoXxw0mOoO6WtjC063CtU1yLcRA6ovEhI97y_KeulSLp7ojQzs1PvU14FHILVKgSDynRCOhrcJqeujbulk7TQ-NABKbAnkyzCg0mEB66aadoBQ-4MjJ1eqJ09hzMdHLYXDDNAQWcea3hlomikNr1w12drlgVOYLm2EN9mS9kZIcSuU-2EXEhCqG_kYeJjfDRcmw7ZqcQFM-bXnYw4UlN2OAaJLXbTLcxrwi4wWV0EjBIEEs-JJIMK0hD4i0LtMcsS4QhlSWpjk74ZIHh8PkI8YQLWBShXSCPpHB6QYBa1K5TYKaFOa1tFCc46_V0RDNlX2ktxgUIZVHZ7HIJSGA2AcDEMmj99kiUaiIZFW3A1H-muyrXH_ccmxGvNlQTQIWunH7wjQrh8CEjyd8TfTA1XRuI3RqB2QgxpkgtcOTjPS0K-BhxaW4Xu09mcDvAG1TiX2RKqdeIeQdzW-RewrJjfkhNWAWVsYBMBwTDWXO0t10wxDUWUQp9kxzPUSj_nwJb-n2OeyJ6U7hdyw_H-UbkmUrsMmjc8t2eq6sP5igXyvbq8-TNxe47WEx6Yh2JSuISXSF9EwjEmyHhIdzSq9qu3UzBvCvJQmIJgl2gZkz3LYOoDts8wRAEbfqBDvCC6guwDUasUmmVwFab2_3hmbPh_QuCJKNsKJb_09NIYiKi819UvNc2qEaESZvgUVD3edURYHy0juTffzTyYDfDtJi2buri9oIzwaakdHrXwtpo-feCV734cKPMSsF9epuLZDK54k6E5hIG_CYdmxj2xzapHOE0gi_DEO06owiuVhL19BumILfTLQiM3JJNo2HRVCwNzV3tC_Wj4LUYIDl3MLkOF

**Comment by prasadtalasila** [comment]
the [wiki page](https://github.com/AutolabJS/autolabcli/wiki/Call-graphs-(Sequence-diagrams)) has been updated with the sequence diagrams. Further updates can take place on this page.

**Comment by prasadtalasila** [comment]
primary work is done. closing the issue.
