### ISSUE TITLE
branch pruning

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#22]
### Description

We have two extra branches with snyk- prefix. The only change in these branches is the bump up of socket.io client library version. Please update the package.json and remove both these branches.

### Steps to Reproduce
The snyk- branches exist in the repository.

**Expected behavior:**

Only master and dev branches are to exist in the repository.

**Comment by SebastinSanty** [comment]
Done. dev was rebased with master which had the synk-bot update.

**Comment by prasadtalasila** [comment]
Thanks @SebastinSanty
