### ISSUE TITLE
Timeout to an evaluation request

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#25]
### Description

A pending evaluation request never times out. If for any reason, the evaluation result does not come back from AutolabJS, the client is in deadlock state. We need a timeout mechanism in `lib/submit.js`.

### Steps to Reproduce

1. As an instructor, create a lab with a simple and single test case (method does sum of two numbers).
2. Write an infinite loop for student submission.
3. Submit evaluation request using `autolab git submit`.
4. The terminal hangs forever

**Expected behavior:** The command times out after 4 minutes.

**Actual behavior:** The command hangs forever

**Reproduces how often:** Only with faulty submission

### Additional Information

We can solve the problem by putting a timeout logic in `lib/submit.js`. A suggested code fragment is given below.    
```js
setTimeout(function() {
  console.error('The evaluation request is taking too long. Exiting now.');
  process.exit(-2);
}, 240000);	//set a timeout of 4 minutes
```

This code fragment can be inserted between lines 11-12 of [lib/submit.js](https://github.com/AutolabJS/autolabcli/blob/master/lib/submit.js)

@SebastinSanty, if you are okay with this change, please go ahead and make a commit on the dev branch.

**Comment by SebastinSanty** [comment]
Closed #25 via #26
