### ISSUE TITLE
autolab submit command not working

### ISSUE THREAD

**Issue by SebastinSanty** [AutolabJS/autolabcli#27]
### Description

`autolab submit` is giving the following error message:

```
Submitting results. Please wait ...Access Denied. Please try submitting again
```

**Comment by AnkshitJain** [comment]
@prasadtalasila This issue was faced in two scenarios.
1. Lab not setup on Autolab server
2. Student repository does not have the required repository. 
Is "Access Denied " the standard response in such cases?

**Comment by prasadtalasila** [comment]
@AnkshitJain When students do not have the repository in GitLab, the evaluation results come back as zero for all the testcases. Only when the main server returns an invalid socket.io event, do you get the "access denied" message. Please see [line-40 of submit.js](https://github.com/AutolabJS/autolabcli/blob/master/lib/submit.js#L40). Such an event happens only under two conditions.

1. There is no valid lab matching the request. [line 395 of main_server.js](https://github.com/AutolabJS/AutolabJS/blob/master/main_server/main_server.js#L395)
2. The evaluation request is submitted with an invalid id number / commit hash. [lines 335-344 of main_server.js](https://github.com/AutolabJS/AutolabJS/blob/master/main_server/main_server.js#L335-L344).

**Comment by prasadtalasila** [comment]
This work is being tracked through [refactoring wiki](https://github.com/AutolabJS/autolabcli/wiki/Refactoring-scratch-pad) page. Not a priority now.
