### ISSUE TITLE
Migrate to CaporalJS framework

### ISSUE THREAD

**Issue by SebastinSanty** [AutolabJS/autolabcli#3]
[CaporalJS](https://github.com/mattallty/Caporal.js?) is a full-featured framework for building command line applications (cli) with node.js. Many of the independent libraries we are using currently, have been strung together in caporal. Hence, a lot of the logic part of the code can be easily migrated without much rewriting.

**Comment by prasadtalasila** [comment]
caporal code has the following programming idiom....
 
```javascript
  .command()
  .argument()
  .option()
  .action(function(args, options, logger) {
    //work done here
  });
```

**Comment by prasadtalasila** [comment]
next version of autolabcli is being developed with caporal.js.
