### ISSUE TITLE
login problems for passwords with special characters

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#32]
### Description
Autolab is giving me invalid username / password even though when i tried to login on the gitlab site. My password has special characters in it. When I changed the password to one without any special characters, the login went through smoothly.

[Description of the issue]
Failed login.

### Steps to Reproduce

1. Create a login account with password having special characters
2. Login to gitlab using autolabcli
3. See the login failure

**Expected behavior:** [What you expect to happen]
Login should be successful for any kind of password.

**Actual behavior:** [What actually happens]
Login fails if password has special characters

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time when used as described above.

**Comment by prasadtalasila** [comment]
All the current efforts shall be directed towards creating a backward compatible Autolabcli. The new code shall be available in [autolabcli-ng](https://github.com/AutolabJS/autolabcli/tree/autolabcli-ng) branch.

**Comment by prasadtalasila** [comment]
Even the new version of autolabjs has this issue. We need to resolve this problem.

**Comment by mukkachaitanya** [comment]
This has been addressed in PR #92

**Comment by prasadtalasila** [comment]
@mukkachaitanya please provide example passwords that failed before and reference to the code fragment that fixed the error.

**Comment by mukkachaitanya** [comment]
### Error

The error was found for cases where the password containing special characters like `#, %`, etc.  For example; a password of the kind `test#1234` would give an `Invalid Username or Password` error. 

### Fix

[L8](https://github.com/AutolabJS/autolabcli/blob/7d700c5ad3145f67670b9fe258d73caf817563f9/lib/model/init.js#L8) of `model/init.js` fixes the issue.
