### ISSUE TITLE
Add AutolabJS as a dev dependency while installation

### ISSUE THREAD

**Issue by SebastinSanty** [AutolabJS/autolabcli#5]
We can replicate the relevant work done in travis.yml of autolab. Done this way, we can avoid bandwidth heavy installation of complete autolab (using vagrant), and also have the [travis.yml](https://github.com/AutolabJS/AutolabJS/blob/master/.travis.yml) setup ready for autolabcli.

This can be the standard autolab setup for all autolabcli developers. Hence, update the existing travis.yml setup to have the autolab run as a dependency. Check this [gist](https://gist.github.com/prasadtalasila/f2e946d37148f3ab37a01622054fce6a) to accomplish the task.

All the setup steps given in the above mentioned gist can be placed in a shell script (test/setup.sh). All autolabcli developers have to do is clone autolabcli and run the script. The setup gets taken care of automatically.

**Comment by prasadtalasila** [comment]
This is not a priority right now.
