### ISSUE TITLE
npm module path

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#51]
### Description
npm should use the locally installed modules. At the moment, npm uses the globally installed modules.

### Steps to Reproduce

1. Remove global installation of any of the dependencies
2. Remove global installation of autolabjs cli
3. Run autolabjs cli

**Expected behavior:** [What you expect to happen]
npm picks up the local module installations and runs the autolabjs cli from the current directory.

**Actual behavior:** [What actually happens]
1. autolabjs fails to run if not installed globally
1. npm uses global modules

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time autolabjs cli is used.

**Comment by 1AmNegan** [comment]
I don't understand how to reproduce the issue. After step 2, do I need to reinstall autolabjs?

**Comment by prasadtalasila** [comment]
That's the point. How can we run autolabjs with all its local dependencies without installing? Is there an npm path specification that we can put in package.json so that we can access the local node_modules and index.js?

**Comment by 1AmNegan** [comment]
If the local modules are installed using  ``npm install``, npm first considers these modules by default. Only if they are not available, npm looks into the global modules. The "bin" property in package.json indicates the entry point of the application, which is index.js.

**Comment by prasadtalasila** [comment]
The code works by using the following procedure.

1. clone autolabcli-ng branch.
1. In the directory, do `npm install`
1. Execute the necessary commands using `node index.js <command>`
