### ISSUE TITLE
Implementation of preferences in autolabjs CLI

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#53]
### Description
The next commands to implement are as follows.
```
autolabjs prefs show
autolabjs prefs changeserver
autolabjs prefs changelang
```

**Comment by prasadtalasila** [comment]
The preferences are to be stored in the `~/.autolabjs` directory with the following naming conventions.
* **locations.json** ---> stores a json map of lab name and the lab directory. This is used to detect the correct execution of autolabjs commands and to eliminate the execution of autolabjs commands in the wrong directory.
* **prefs.json** ---> stores the user preferences.
* **credentials.json** ---> stores the user credentials. These credentials need to timeout after two hours.

@1AmNegan please note the suggestion to include changes when the new code for preferences is brought in.

**Comment by 1AmNegan** [comment]
What should be the default lab directory? Can we make it the current directory in which 'init' command was executed?

**Comment by prasadtalasila** [comment]
Sine locations.json is only used for git commands, we will not modify this file further till code for git commands are put in place.

**Comment by 1AmNegan** [comment]
Can I get a list of languages and the exact string expected by the server for each language?

**Comment by AnkshitJain** [comment]
@1AmNegan The languages are `c`, `cpp`, `cpp14`, `java`, `python2`, `python3`.

**Comment by prasadtalasila** [comment]
@1AmNegan Another hard assumption we are making is that all the labs submitted by a student shall be in one preferred programming language. Is there an advantage to having a lab-specific language preference? We can easily store such an information in `locations.json`.

I have personally not seen students change their preferred language frequently during the course of a semester, forget about a lab. The maximum I have seen is a switch of two languages: typically, java --> python --> cpp. The most usual case of language change is simply one switch in a semester.

@AnkshitJain your ideas on this feature would be good.

**Comment by prasadtalasila** [comment]
Another brain storming question:
How appropriate is it to show a table of lab name and its location along with preferences as an output of `autolabjs prefs show` command?

**Comment by prasadtalasila** [comment]
Sounds good. We shall have to deduce the submission languages from the directory contents.

**Comment by prasadtalasila** [comment]
PR #57 implements the required features.
