### ISSUE TITLE
application architecture

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#6]
We can use an MVC architecture to separate the UI from controller and program logic. Done properly, we can easily change the view to make the autolabctl application work in GUI mode. Considering the choice of commandline / GUI mode usage, it is better to use electron-base to build the application.

Even within electron SDK, we can still use caporal.js for cli scenario.

**Comment by SebastinSanty** [comment]
Just to note: I have used electron earlier. One of the main disadvantages I have felt is, the minimum package size of an electron application is ~50mb, for even a "Hello World" app.

**Comment by prasadtalasila** [comment]
I was not aware of that. But, that cost may be worth paying for only after having decently useful functionality in autolabcli.

Still, the separation of UI from the library (functionality) and controller would still be useful.

**Comment by prasadtalasila** [comment]
More importantly, at 50MB size, Electron is going to bring in millions of lines of code into the application as a dependency. Is that really high quality code?

**Comment by prasadtalasila** [comment]
electron-based design is abandoned for now because of size constraints. The CLI-based architecture has been placed in [Refactoring page](https://github.com/AutolabJS/autolabcli/wiki/Refactoring-scratch-pad).
