### ISSUE TITLE
Separate test coverage reports

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#65]
### Description
The test coverage reports need to be separated and reported to different websites.
* unit tests to codecov
* integration tests to codeclimate
* feature tests to coveralls

Also see #61 for the relevant commands to run different kinds of tests.

**Comment by 1AmNegan** [comment]
There is a provision for providing `token` in `codecov.yml`, but it does not seem to be working. There is also an [issue](https://github.com/codecov/codecov-node/issues/64) regarding this. So, I will stick to the format of providing the token when running the `post-feature` command.

**Comment by 1AmNegan** [comment]
[Autolabcli tests](https://github.com/AutolabJS/autolabcli/wiki/Autolabcli-tests) page is updated.
