### ISSUE TITLE
grunt vs npm

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#7]
At present, we are using grunt to manage the liting, testing. In future, we may use grunt to package the application as well. Since npm is perfectly capable of performing all these steps, is there any distinct advantage to using grunt over npm?

**Comment by utkarshrai** [comment]
I want to take this issue. I believe shifting only to npm is a better idea(without grunt).
Spent some time looking at others experiences with grunt and there were multiple reported problems using grunt over time; and how simply it was not needed.
No grunt would mean less package dependencies. 
I tried using grunty but that was another overhead and we should shift to npm only.

**Comment by prasadtalasila** [comment]
@SebastinSanty please comment on this before @utkarshrai starts off down this road.

**Comment by SebastinSanty** [comment]
@prasadtalasila I had discussed with @utkarshrai extensively on this topic, and hence his comments reflect some of my opinions too.

**Comment by SebastinSanty** [comment]
Grunt has been removed. And now the build and tests are based on npm completely. Thanks @utkarshrai for the contribution.
