### ISSUE TITLE
Implement autolabjs eval command

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#77]
Implement `autolabjs eval` command using the option conventions followed in [submit.js](https://github.com/AutolabJS/AutolabJS/blob/master/tests/test_modules/submit.js).

**Comment by 1AmNegan** [comment]
@prasadtalasila  Do I need to create flags for lang, or can I just read it from stored preferences?

**Comment by 1AmNegan** [comment]
`-i <student_id>: optional flag, only allowed when the logged in user is root`
@prasadtalasila  Does this mean the student must be logged in before s/he makes a submission? Isn't this counter-intuitive for bulk evaluation?

**Comment by prasadtalasila** [comment]
We discussed about allowing evaluations of only logged in users. We allow the student id flag only for `root` user. Only `root` user (alias instructor) is allowed to perform the bulk evaluation.

**Comment by prasadtalasila** [comment]
PR #78 closes the issue.
