### ISSUE TITLE
linting errors in test/*.js and mocha test errors due to `host` undefined.

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#8]
### Description

travis build failure

### Steps to Reproduce

Please see the [travis build log](https://travis-ci.org/AutolabJS/autolabcli/builds/235251887#L604)

**Comment by SebastinSanty** [comment]
Is this safe to be closed?

**Comment by prasadtalasila** [comment]
The [builds](https://travis-ci.org/AutolabJS/autolabcli/builds) are still failing. We need to fix that before we can close the issue.

**Comment by SebastinSanty** [comment]
The error was due to, not initializing the preferences(package) variables before mocha test. A before script has been added to grunt to run `node index.js`.
