### ISSUE TITLE
Remove unwanted output after feature tests

### ISSUE THREAD

**Issue by 1AmNegan** [AutolabJS/autolabcli#83]
### Description

The console shows `Evaluating you submission, please wait...` even after the feature test are complete.

### Steps to Reproduce

`npm run feature`

**Expected behavior:** There should be no output in the terminal after the feature tests are complete.

**Actual behavior:** The terminal shows `Evaluating you submission, please wait...` even after the feature test are complete.

**Reproduces how often:** Everytime

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by prasadtalasila** [comment]
PR #78 closes the issue.
