### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/autolabcli#85]
### Description
Update the documentation for the following wiki pages.
1. Module structure - package diagrams, sequence diagrams    
     samples to look at: [call graphs](https://github.com/AutolabJS/autolabcli/wiki/AutolabcliNG), [file structure](https://github.com/AutolabJS/AutolabJS/wiki/Test-Structure)
1. Documentation for TDD (look at AutolabJS testing documentation)
1. Update [Events doc](https://github.com/AutolabJS/autolabcli/wiki/Events-Doc) - categorization of existing events along with table for all the modules that use the events; general advice on the format and semantics of the JSON structures.
1. [Libraries](https://github.com/AutolabJS/autolabcli/wiki/Notes-on-Libraries)
1. [Install instructions](https://github.com/AutolabJS/autolabcli/wiki/v2.0.0-Installation)
1. [submission instructions](https://github.com/AutolabJS/autolabcli/wiki/v2.0.0-Assignment-Submission-using-autolab-CLI)
1. Create an FAQ page on design questions and user questions.
1. Page outlining steps to be followed for adding new features to autolabcli

**Comment by prasadtalasila** [comment]
@mukkachaitanya Only the package diagram is pending. Please remove the existing image and add the package diagram to [module structure](https://github.com/AutolabJS/autolabcli/wiki/Module-Structure) page.

**Comment by mukkachaitanya** [comment]
The package diagram has been updated at [module structure](https://github.com/AutolabJS/autolabcli/wiki/Module-Structure) page.

**Comment by prasadtalasila** [comment]
@mukkachaitanya The module diagrams seem incomplete. Please use [madge](https://github.com/pahen/madge) to cross-verify the diagram.
Madge is not able to parse some of the modules that have dependency on modules with name `eval.js`. The problem has been described in issue #93.

An incomplete diagram generated by madge is given below.
![deps](https://user-images.githubusercontent.com/9206466/46878390-7708db80-ce43-11e8-81aa-637e0ae91fed.png)

**Comment by prasadtalasila** [comment]
Please update the README.md with the latest changes in the commands and options including the debug option. This can be done in the next PR.

**Comment by mukkachaitanya** [comment]
These changes have been completed.
